### PR TITLE
Bogus safety violation checking if a set is a subset of Nat.

### PR DESCRIPTION
**Pull request by lemmy**
Fixes Github issue #2948
https://github.com/apalache-mc/apalache/issues/2948

### CODE REVIEW

**Comment by lemmy** [comment]
5724d0d causes Apalache to report a proper error message: `SetInRule is not implemented for type PowSet[Set(Int)] (found in {1, 2, 3, 4} ∈ SUBSET Nat)`.

**Comment by lemmy** [comment]
@thpani @konnov https://github.com/apalache-mc/apalache/commit/c69c355877ea306e38eaf53212ba779efa14318b and https://github.com/apalache-mc/apalache/commit/830caa71596caf488b7717b39ba2a4e535ddb779 cause Apalache to no longer hit this code path for the given inputs (the expressions are rewritten elsewhere). Would you like to add the safeguard below anyway?  If you do, I'll update the tests to expect the corresponding error message.

https://github.com/apalache-mc/apalache/pull/2960/files#diff-455ee0089c33ede12710ae233adedc17473d8ac7cc6a2ca7246f127a7482512aR58-R60

**Comment by lemmy** [comment]
@konnov This PR does not aim to extend the encoding. Instead, it ensures that Apalache throws an error when an infinite set is encountered in a context where it isn't properly handled.

**Comment by konnov** [comment]
Ah, sorry, I missed that. Yes, this makes sense  to add. Thanks a lot!

**Review by konnov — APPROVED** [review]
A safeguard would definitely help!

**Comment by lemmy** [comment]
This is ready for review and merging. Although commits c69c355877ea306e38eaf53212ba779efa14318b and 830caa71596caf488b7717b39ba2a4e535ddb779 prevent any of the three encodings from reporting a bogus invariant violation for expressions like `{1, 2, 3} \in SUBSET Nat` (due to rewriting), this update ensures that Apalache generates a clear error message when handling infinite sets, should the rewrites ever be removed in the future.

**Review by konnov — APPROVED** [review]
This makes sense! Thanks for adding the safeguards

**Comment by konnov** [comment]
I cannot add an entry in `.unchanged`, since it's your PR. Could you add one?

**Comment by lemmy** [comment]
What should that entry be?

**Comment by konnov** [comment]
> What should that entry be?

Oh, just one line describing the nature of the change, see https://github.com/apalache-mc/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

I guess, it should technically go into [bug-fixes](https://github.com/apalache-mc/apalache/tree/main/.unreleased/bug-fixes).

**Comment by lemmy** [comment]
done

**Review by thpani — APPROVED** [review]
LGTM

**Pull request merged**
